### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by matkoniecz** [docentYT/osm_easy_api#27]
```
  File "/home/mateusz/.local/lib/python3.10/site-packages/osm_easy_api/api/endpoints/changeset_discussion.py", line 23, in comment
    response = self.outer._request(self.outer._RequestMethods.POST, self.outer._url.changeset_discussion["comment"].format(id=changeset_id, text=urllib.parse.quote(text)), self.outer._Requirement.YES, auto_status_code_handling=False)
  File "/usr/lib/python3.10/urllib/parse.py", line 881, in quote
    return quote_from_bytes(string, safe)
  File "/usr/lib/python3.10/urllib/parse.py", line 906, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
```

**Comment by matkoniecz** [comment]
happened when I tried to pass `None` instead of comment text, so I guess that crash is not terrible?

**Comment by docentYT** [comment]
Do I understand correctly that you are trying to add a comment that does not contain any text to changeset?
Additionally, in the [documentation](https://docentyt.github.io/osm_easy_api/osm_easy_api/api/endpoints/changeset_discussion.html#Changeset_Discussion_Container.comment) as well as in the code, the `text` parameter should be of type string.

The OpenStreetMap api returns an error 400 when no text is specified anyway.

**Comment by matkoniecz** [comment]
I specified `None` and git this unexpected crash
