### ISSUE TITLE
Support ancient anonymous edits

### ISSUE THREAD

**Issue by matkoniecz** [docentYT/osm_easy_api#4]
This tool works really nice, but it has some problems when dealing OSM prehistorical oddities.

Trying to fetch history of https://www.openstreetmap.org/node/25733488/history results in

```
  File "/home/mateusz/.local/lib/python3.10/site-packages/osm_easy_api/api/endpoints/elements.py", line 167, in history
    objects_list.append(_element_to_osm_object(elem))
  File "/home/mateusz/.local/lib/python3.10/site-packages/osm_easy_api/diff/diff_parser.py", line 126, in _element_to_osm_object
    node = _create_node_from_attributes(element.attrib)
  File "/home/mateusz/.local/lib/python3.10/site-packages/osm_easy_api/diff/diff_parser.py", line 88, in _create_node_from_attributes
    user_id =       int(    attributes["uid"]       ),
KeyError: 'uid'
```

note, users can be also deleted - it may cause a similar issue

**Comment by docentYT** [comment]
The simplest solution would be to set the user_id value to 0 or -1 for anonymous or deleted users.  Do you think this is a good solution?

**Comment by matkoniecz** [comment]
Why not `None`? That, I think, more clearly express that in this case there is no matching account, better than magic codes.

**Comment by docentYT** [comment]
Not `None` because some requests to the api do not return all the data that apply to the node, for example. A value of `None` in this case could mean either that the full information needs to be downloaded or that there is no user.

**Comment by matkoniecz** [comment]
then -1 is needed I guess :/

**Comment by matkoniecz** [comment]
Seems better than 0 for clear indication that is not an actual user.

**Comment by docentYT** [comment]
https://github.com/docentYT/osm_easy_api/releases/tag/v0.2.0
