### ISSUE TITLE
ability to provide custom user_agent would be nice

### ISSUE THREAD

**Issue by matkoniecz** [docentYT/osm_easy_api#5]
Especially as APIs often block/rate limit queries without user agent or ones being abusive

**Comment by docentYT** [comment]
Better to make the possibility of setting the user_agent global for all modules or separately for API and diff?

**Comment by docentYT** [comment]
https://github.com/docentYT/osm_easy_api/tree/development

**Comment by docentYT** [comment]
https://github.com/docentYT/osm_easy_api/releases/tag/v0.3.0
