### ISSUE TITLE
ability to serialize/deserialize changeset from JSON would be nice

### ISSUE THREAD

**Issue by matkoniecz** [docentYT/osm_easy_api#7]
https://github.com/docentYT/osm_easy_api/blob/main/src/osm_easy_api/data_classes/changeset.py

Again, pickling cannot be used as it would allow people crafting changeset with weird tag and take over my computer.

And this would be interesting, but really embarrassing.

**Comment by matkoniecz** [comment]
As I understand - https://github.com/docentYT/osm_easy_api/commit/19f5c45aa9dcfb251d426a50a9edfbb2133a6ee1 is not covering changesets.

**Comment by docentYT** [comment]
https://github.com/docentYT/osm_easy_api/releases/tag/v0.3.0
