### ISSUE TITLE
Maybe show xml on parse failure?

### ISSUE THREAD

**Issue by matkoniecz** [docentYT/osm_easy_api#9]
```
  File "/home/mateusz/.local/lib/python3.10/site-packages/osm_easy_api/api/endpoints/elements.py", line 165, in history
    for event, elem in generator:
  File "/home/mateusz/.local/lib/python3.10/site-packages/osm_easy_api/api/api.py", line 65, in _raw_stream_parser
    for event, element in iterator:
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1253, in iterator
    yield from pullparser.read_events()
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1324, in read_events
    raise event
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1296, in feed
    self._parser.feed(data)
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0
```

I strongly suspect that OSM API returned some error for whatever reason. Would be nice if osm_easy_api would show its contents before crashing.

**Comment by matkoniecz** [comment]
happens sometimes on

```
from osm_easy_api import Api
from osm_easy_api.data_classes import Node, Way, Relation, Changeset, OsmChange, Action, Tags

api = Api(url='https://openstreetmap.org')
api.elements.history(Way, 250066046)
```

https://www.openstreetmap.org/way/250066046/history

I see nothing weird in https://api.openstreetmap.org/api/0.6/way/250066046/history but maybe invisible control characters or something is causing problems

also happened few times, then stopped - maybe server was returning error?

**Comment by matkoniecz** [comment]
https://api.openstreetmap.org/api/0.6/way/250066046/history is for me responding with 

`You have downloaded too much data. Please try again later.`

Full response is:

```
<html><head><link rel="stylesheet" href="resource://content-accessible/plaintext.css"><title> | https://api.openstreetmap.org/</title></head><body><pre>You have downloaded too much data. Please try again later.</pre></body></html>
```

**Comment by docentYT** [comment]
> `You have downloaded too much data. Please try again later.`

According to the [wiki](https://wiki.openstreetmap.org/wiki/API_v0.6), this error only occurs with one endpoint `GET /api/0.6/map`:
> HTTP status code 509 (Bandwidth Limit Exceeded)
"Error: You have downloaded too much data. Please try again later." See [Developer FAQ](https://wiki.openstreetmap.org/wiki/Developer_FAQ#I've_been_blocked_from_the_API_for_downloading_too_much._Now_what?).

In that case, either this is not a 509 error or the wiki is incomplete. If you get this error next time please check what http code it is.

**Comment by matkoniecz** [comment]
> According to the [wiki](https://wiki.openstreetmap.org/wiki/API_v0.6), this error only occurs with one endpoint GET /api/0.6/map:

Maybe it is the most likely there, but if I look at code right it can be triggered by any API call if you download too much data and become rate limited.

> "Error: You have downloaded too much data. Please try again later." See [Developer FAQ](https://wiki.openstreetmap.org/wiki/Developer_FAQ#I've_been_blocked_from_the_API_for_downloading_too_much._Now_what?).

This page was heavily outdated, for example it mentioned XAPI before my edit.

> If you get this error next time please check what http code it is.

I will reopen it once I have answer to that.
